# downloading  nginx ...
docker pull nginx:1.17.1

# downloading  zookeeper ...
docker pull zookeeper:3.5.5

# downloading  redis ...
docker pull redis:5.0.5

# downloading  openldap ...
docker pull osixia/openldap:1.2.4

# downloading  mysql ...
docker pull mysql:5.6.45

# downloading  oracle ...
docker pull yunql/oracle-xe-11gr2-zh:1.0.0

# downloading  tomcat ...
docker pull tomcat:8.5.34

# downloading  portainer ...
docker pull portainer/portainer:1.21.0
