rem downloading  nginx ...
docker pull nginx:1.17.1

rem downloading  zookeeper ...
docker pull zookeeper:3.5.5

rem downloading  redis ...
docker pull redis:5.0.5

rem downloading  openldap ...
docker pull osixia/openldap:1.2.4

rem downloading  mysql ...
docker pull mysql:5.6.45

rem downloading  oracle ...
docker pull yunql/oracle-xe-11gr2-zh:1.0.0

rem downloading  tomcat ...
docker pull tomcat:8.5.34

rem downloading  portainer ...
docker pull portainer/portainer:1.21.0
