drop table DUBBO_INVOKE;
create table DUBBO_INVOKE
(
	ID VARCHAR2(255) not null
		primary key,
	INVOKE_DATE DATE not null,
	SERVICE VARCHAR2(255) default NULL,
	METHOD VARCHAR2(255) default NULL,
	CONSUMER VARCHAR2(255) default NULL,
	PROVIDER VARCHAR2(255) default NULL,
	TYPE VARCHAR2(255) default '',
	INVOKE_TIME NUMBER(20) default NULL,
	SUCCESS NUMBER(11) default NULL,
	FAILURE NUMBER(11) default NULL,
	ELAPSED NUMBER(11) default NULL,
	CONCURRENT NUMBER(11) default NULL,
	MAX_ELAPSED NUMBER(11) default NULL,
	MAX_CONCURRENT NUMBER(11) default NULL
);
