echo 创建 dasc 数据库 ...
mysql -uroot -pMysql.8784</var/lib/mysql/dasc-db.sql
echo 导入 dasc 数据表 ...
mysql -uroot -pMysql.8784 -Ddasc</var/lib/mysql/dasc-tb.sql
echo 创建 dubbo-monitor 数据库 ...
mysql -uroot -pMysql.8784 -Ddasc</var/lib/mysql/dubbo-monitor.sql
echo 导入 dasc 开发环境配置 ...
mysql -uroot -pMysql.8784 -Ddasc</var/lib/mysql/dasc-dev.sql